# Generated by Django 5.1 on 2025-08-30 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('ca_numero', models.CharField(max_length=50, verbose_name='Número do CA')),
                ('data_validade_ca', models.DateField(verbose_name='Data de Validade do CA')),
                ('quantidade_total', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField()),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='ATIVO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aluguel.epi', verbose_name='EPI')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_recebidos', to='aluguel.usuarios', verbose_name='Colaborador')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_realizados', to='aluguel.usuarios', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
