# Generated by Django 5.1 on 2025-08-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='login',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('TECNICO', 'Tecnico de segurança'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
