# Generated by Django 5.1 on 2025-09-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_alter_usuarios_login_alter_usuarios_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='observacao',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='condicoes_emprestimo',
            field=models.TextField(blank=True, null=True, verbose_name='Condições no Empréstimo'),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='data_prevista_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista da Devolução'),
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='observacao_devolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação na Devolução/Perda'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_retirada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo'),
        ),
    ]
