# Generated by Django 5.1 on 2025-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0003_remove_emprestimos_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='status',
            field=models.CharField(choices=[('EMPRESTADO', 'Emprestado'), ('FORNECIDO', 'Fornecido'), ('DEVOLVIDO', 'Devolvido'), ('DANIFICADO', 'Danificado'), ('PERDIDO', 'Perdido')], default='EMPRESTADO', max_length=20),
        ),
    ]
